plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Claude ai\\OstazAI\\website\\platform\\dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "D:\\Claude ai\\OstazAI\\website\\platform"
command = "expo export -p web"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]