import { readFileSync, writeFileSync } from 'fs';
let src = readFileSync('app.js', 'utf8');

const WORKED = {
  'Number': 'LCM of 12 and 18:\n12=2²×3, 18=2×3²\nLCM=2²×3²=36\nHCF=2×3=6\nStandard form: 0.00307=3.07×10⁻³\n(4×10⁵)÷(8×10²)=0.5×10³=5×10²',
  'Number Types & Operations': 'Prime factorisation of 360:\n360=2×180=2×2×90=2²×2×45=2³×3²×5\nHCF(360,252): 252=2²×3²×7 → HCF=2²×3²=36\nLCM=2³×3²×5×7=2520',
  'Number Systems': 'Convert 10110₂ to decimal:\n1×16+0×8+1×4+1×2+0×1=22\nConvert 45 to binary: 45÷2=22r1, 22÷2=11r0, 11÷2=5r1, 5÷2=2r1, 2÷2=1r0, 1÷2=0r1 → 101101₂',
  'Fractions, Ratios & Percentages': 'Ratio 3:5, total=£240. Share:\nEach part=£240/8=£30. Shares: £90, £150.\nFraction: ³⁄₄ of 360=270\nPercentage: 72 as % of 96=(72/96)×100=75%',
  'Percentages, Ratio & Proportion': 'Increase £450 by 15%: 450×1.15=£517.50\nDecrease by 12%: 450×0.88=£396\nReverse: after 20% increase price=£600. Original=600/1.2=£500',
  'Algebra & Graphs': 'Solve 2x²-8=0:\n2x²=8 → x²=4 → x=±2\nSketch y=x²-4: roots at x=±2, minimum at (0,-4)',
  'Algebraic Manipulation': 'Factorise 6x²+7x-3:\nFind pair: 6×(-3)=-18; pair summing to 7: 9,-2\n6x²+9x-2x-3=3x(2x+3)-(2x+3)=(3x-1)(2x+3)',
  'Equations & Inequalities': 'Solve |3x-2|≤7:\n-7≤3x-2≤7 → -5≤3x≤9 → -5/3≤x≤3\nQuadratic inequality x²-5x+6>0:\n(x-2)(x-3)>0 → x<2 or x>3',
  'Graphs & Functions': 'f(x)=2x+1, g(x)=x². Find fg(3) and gf(3).\nfg(3)=f(9)=19; gf(3)=g(7)=49\nInverse: f⁻¹(x)=(x-1)/2',
  'Functions': 'f(x)=3x-5. Find f⁻¹(x).\ny=3x-5 → x=(y+5)/3 → f⁻¹(x)=(x+5)/3\nff⁻¹(x)=f((x+5)/3)=3·(x+5)/3-5=x ✓',
  'Functions & Their Graphs': 'Exponential: y=2×3ˣ. When x=0: y=2. When x=2: y=18.\nGrowth factor=3. To find x when y=54: 3ˣ=27 → x=3\nLog form: x=log₃27=3 ✓',
  'Coordinate Geometry': 'Line through (2,5) and (6,13):\nGradient=(13-5)/(6-2)=2\ny-5=2(x-2) → y=2x+1\nMidpoint=(4,9). Distance=√(16+64)=√80=4√5',
  'Lines & Circles': 'Circle x²+y²-6x+4y-12=0. Find centre and radius.\nComplete square: (x-3)²-9+(y+2)²-4-12=0\n(x-3)²+(y+2)²=25 → centre (3,-2), radius 5',
  'Geometry': 'Exterior angle of regular polygon=360°/n\nFor hexagon: 360°/6=60°. Interior=120°.\nSum of interior angles=(n-2)×180°=720° for hexagon',
  'Angle Properties': 'Parallel lines cut by transversal:\nAlternate angles equal (Z-angles): both=65°\nCo-interior angles supplementary: 65°+115°=180°\nCorresponding angles equal (F-angles)',
  'Similarity & Congruence': 'Triangles ABC and PQR similar. AB=6, BC=9, PQ=4.\nScale factor=4/6=⅔. QR=9×⅔=6.\nArea ratio=(⅔)²=4/9. If area ABC=27: area PQR=12',
  'Mensuration': 'Frustum: top radius 3cm, bottom 6cm, height 8cm.\nRemove cone: total height h satisfies 3/6=h/(h+8) → h=8.\nVolume frustum=⅓π(6²×16-3²×8)=⅓π(576-72)=168π≈528cm³',
  'Areas & Perimeters': 'Composite shape: rectangle 10×6 with semicircle on top (radius 3).\nArea=60+½π×9=60+14.14=74.14cm²\nPerimeter=10+6+6+½×2π×3=10+12+9.42=31.42cm (no top edge)',
  'Volumes & Surface Areas': 'Sphere: radius 5cm. Volume=⁴⁄₃π×125=523.6cm³\nSurface area=4π×25=314.2cm²\nCylinder: r=4, h=10. V=π×16×10=502.7cm³. SA=2π×4×10+2π×16=351.9cm²',
  'Vectors & Transformations': 'ABCD parallelogram. AB⃗=a, AD⃗=b.\nAC⃗=a+b, BD⃗=b-a\nMidpoint M of AC: AM⃗=½(a+b)\nRotation 90° anticlockwise: (x,y)→(-y,x)\nPoint (3,4)→(-4,3)',
  'Vectors': 'p=(5,2), q=(-1,4). Find p+2q and |p+2q|.\np+2q=(5-2, 2+8)=(3,10)\n|p+2q|=√(9+100)=√109≈10.44\nUnit vector of p: p/|p|=(5,2)/√29',
  'Transformations': 'Describe transformation: (x,y)→(x+3, -y+1)\nReflection in y=½ (vertical shift), then translate (3,0)? No:\nThis is reflection in y=½ then translation? Check: reflection in x-axis gives (x,-y), then translate (+3,+1).\n→ Reflection in x-axis then translation by vector (3,1)',
  'Pythagoras, Trigonometry & 3D': 'Right pyramid: square base 8cm, height 6cm.\nSlant edge: base diagonal=8√2, half=4√2.\nSlant edge=√((4√2)²+6²)=√(32+36)=√68=2√17≈8.25cm\nAngle to base: tan θ=6/(4√2)=6/5.66 → θ=46.7°',
  'Graph Types & Statistics': 'Box plot: min=12, Q1=18, median=24, Q3=32, max=45.\nIQR=32-18=14. Outlier fence: Q3+1.5×IQR=32+21=53 (none here)\nNormal distribution: 68% within 1σ, 95% within 2σ, 99.7% within 3σ',
  'Probability': 'Two dice rolled. P(sum=7):\nFavourable: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1)=6 outcomes\nP=6/36=1/6\nP(at least one 6)=1-P(no 6)=1-(5/6)²=1-25/36=11/36',
  'Statistics': 'Mean of frequency table:\nScore: 1(f=3), 2(f=7), 3(f=12), 4(f=6), 5(f=2). n=30\nΣfx=3+14+36+24+10=87\nMean=87/30=2.9. Median: 15th+16th both in score=3 → median=3',
  'Circle Theorems': 'Points A,B,C,D on circle. AB is diameter.\n∠ACB=90° (angle in semicircle)\nIf ∠ADB=90° too (both subtend same arc AB)\nOpposite angles ABCD cyclic quad: ∠A+∠C=180°',
  'Logarithms': 'Solve log₂(x)+log₂(x-2)=3\nlog₂(x(x-2))=3 → x(x-2)=8\nx²-2x-8=0 → (x-4)(x+2)=0\nx=4 (reject x=-2, log undefined for negative)\nCheck: log₂4+log₂2=2+1=3 ✓',
  'Logarithms & Exponentials': 'Solve 5ˣ=200:\nln(5ˣ)=ln(200) → x·ln5=ln200\nx=ln200/ln5=5.298/1.609=3.292\nOr log: x=log200/log5=2.301/0.699=3.292 ✓',
  'Modulus Function': 'Solve |2x+3|=|x-1|\nCase 1: 2x+3=x-1 → x=-4\nCase 2: 2x+3=-(x-1) → 3x=-2 → x=-⅔\nSketch both: V-shapes intersect at these x-values',
  'Integration': '∫(4x³-6x+2)dx = x⁴-3x²+2x+c\nDefinite: ∫₀² (3x²-4)dx=[x³-4x]₀²=(8-8)-(0)=0\nArea between curve and x-axis: if answer negative, take |result|',
  'Integration Applications': 'Volume of revolution: y=x² from x=0 to x=3 about x-axis.\nV=π∫₀³ x⁴dx=π[x⁵/5]₀³=π×243/5=48.6π≈152.7 units³',
  'Exponential & Log Graphs': 'Population model: P=500×1.03ᵗ\nt=0: P=500; t=10: P=500×1.34=672\nDouble when 1.03ᵗ=2: t=ln2/ln1.03=23.4 years\nGraph: exponential curve, y-intercept=500, always positive, increasing',
  'Algorithms & Complexity': 'Merge sort: split [5,2,8,1,9,3] into halves.\n[5,2,8] and [1,9,3]\nSort each: [2,5,8] and [1,3,9]\nMerge: compare heads → [1,2,3,5,8,9]\nTime complexity O(n log n) vs bubble sort O(n²)',
  'Arrays & File Handling': 'Python array of 5 scores:\nscores=[85,72,91,68,79]\nAverage=sum(scores)/len(scores)=79\nFile: f=open("data.txt","r"); lines=f.readlines(); f.close()\nCSV: reader=csv.reader(f); for row in reader: print(row[0])',
  'CPU Architecture': 'Fetch-Decode-Execute cycle:\n1. Fetch: MAR←PC; MDR←[MAR]; PC++; IR←MDR\n2. Decode: CU decodes instruction in IR\n3. Execute: ALU performs operation; result stored in accumulator\nHarvard architecture: separate memory for data and instructions (faster)\nvon Neumann: shared memory bus (simpler, common)',
  'Computer Architecture': 'CPU performance factors:\nClock speed: 3GHz=3×10⁹ cycles/sec\nCores: quad-core executes 4 streams in parallel\nCache: L1(32KB, fast) < L2(256KB) < L3(8MB, slow)\nRAM: 8GB typical; virtual memory uses HDD as overflow\nSSD vs HDD: SSD faster (no moving parts), more expensive per GB',
  'Computer Hardware Components': 'Fetch instruction at address 0x1A:\nPC=0x1A → MAR=0x1A → fetch from RAM → MDR=instruction → IR←MDR → PC=0x1B\nTransistor counts: modern CPU has 50+ billion transistors at 3-5nm\nMoore\'s Law: transistor count doubles ~every 2 years (slowing now)',
  'Network Fundamentals': 'Star topology: all devices connect to central switch.\nIf one cable fails: only that device affected (not whole network)\nBus topology: one cable; if backbone fails, all fail\nPacket: header (source IP, dest IP, seq number) + data + trailer (checksum)\nTCP: reliable, confirms delivery; UDP: fast, no confirmation (streaming)',
  'Network Types & Topologies': 'LAN vs WAN:\nLAN: within single building/campus; owned by organisation; fast (1Gbps)\nWAN: across cities/countries; uses ISP infrastructure; slower\nPAN: personal area (Bluetooth, <10m)\nWiFi range: 2.4GHz (~45m), 5GHz (~15m but faster)\nIPv4: 32-bit (4.3 billion addresses); IPv6: 128-bit (virtually unlimited)',
  'Cyber Security': 'Caesar cipher key=13 (ROT13): "HELLO"→"URYYB"\nVigenère cipher: polyalphabetic, harder to crack\nRSA: public key (n,e), private key (n,d)\nEncrypt: C=Mᵉ mod n; Decrypt: M=Cᵈ mod n\nMD5/SHA-256: hash functions, one-way (cannot reverse)\nDDoS: overwhelm server with requests from thousands of infected machines (botnet)',
  'Cybersecurity': 'Brute force: try every possible password.\n6-char password (a-z): 26⁶=308 million combinations\nSalted hash: add random string before hashing; prevents rainbow table attacks\nTwo-factor authentication: password + one-time code (something you know + something you have)\nFirewall rules: ALLOW port 443 (HTTPS), DENY port 23 (Telnet)',
  'Cybersecurity & Data Protection': 'GDPR principles: lawful basis, data minimisation, accuracy, storage limitation, security\nData breach: must notify ICO within 72 hours\nSQL injection prevention: use prepared statements/parameterised queries\nCross-site scripting (XSS): inject malicious JS into webpage; prevention: sanitise input/output\nEncryption in transit: TLS/HTTPS; at rest: AES-256',
  'Database Concepts': 'Normalisation to 3NF:\n1NF: atomic values, no repeating groups\n2NF: no partial dependencies (every non-key attribute depends on WHOLE key)\n3NF: no transitive dependencies (non-key attributes only depend on key)\nExample: Orders(OrderID, CustomerID, CustomerName) → CustomerName depends on CustomerID (transitive) → move to Customers table',
  'Databases & Spreadsheets': 'VLOOKUP: =VLOOKUP(E2, A2:C10, 3, FALSE)\nLooks for E2 in first column of A2:C10, returns value from 3rd column\nPivot table: drag fields to rows/columns/values; summarise large datasets\nSQL: SELECT AVG(salary) FROM employees WHERE dept="IT" GROUP BY grade HAVING AVG(salary)>50000',
  'Data Handling & Spreadsheets': '=COUNTIF(B2:B20,">=60") counts cells ≥60\n=SUMIF(C2:C20,"Sales",D2:D20) sums D where C="Sales"\nAbsolute reference: $A$1 (locked); relative: A1 (moves when copied)\nNested IF: =IF(A1>=70,"A",IF(A1>=60,"B",IF(A1>=50,"C","F")))',
  'Data Types & Representation': 'Floating point: 0.1101₂ × 2³ (mantissa × 2^exponent)\nActual value: 0.1101₂=0.8125; ×8=6.5\nCharacter encoding: ASCII A=65=01000001₂\nUnicode: UTF-8 uses 1-4 bytes; covers all world languages\nOverflow: 8-bit max=255; 255+1=0 (wraps around)',
  'Memory & Storage': 'Hierarchy (fastest→slowest): registers → cache → RAM → SSD → HDD → tape\nRegisters: CPU, <1ns; Cache: ~1-10ns; RAM: ~100ns; SSD: ~50µs; HDD: ~5ms\n1TB SSD stores: 1×10¹² bytes / 5×10⁶ bytes per MP3 = 200,000 songs\nVirtual memory: page fault → swap page from RAM to disk (slow!)',
  'Hardware & Software': 'Utility software examples: disk defragmenter, antivirus, compression tool, backup software\nOperating system: manages memory allocation, process scheduling (round-robin), file system\nDevice driver: translates OS commands to hardware-specific signals\nMultiprocessing: multiple CPUs; Multitasking: one CPU rapidly switches between processes',
  'Demand': 'Demand curve: P on y-axis, Q on x-axis; downward sloping\nAt P=£10: Qd=500; At P=£15: Qd=300\nPED=(−200/500)÷(5/10)=−0.4/0.5=−0.8 (inelastic)\nShift: income rises → demand for normal goods increases (curve shifts RIGHT)\nShift: price of substitute rises → demand for this good rises (RIGHT)',
  'Elasticity': 'PED=−1.5 means 10% price rise → 15% fall in Qd\nRevenue effect: elastic demand (|PED|>1): price↑ → revenue↓\nInelastic (|PED|<1): price↑ → revenue↑\nPES=0.4: 10% price rise → 4% increase in supply\nPES low for agriculture (fixed land) and short run (capacity constraints)',
  'Economic Policies': 'Expansionary fiscal: cut income tax by 2p → increases disposable income → C rises → AD shifts right\nMultiplier = 1/(1-MPC); if MPC=0.8: multiplier=5\n£1bn stimulus → £5bn increase in GDP (if no leakages)\nMonetary: rate cut from 5%→3%: cheaper mortgages → more consumer spending → AD↑',
  'Economic Systems': 'Free market: prices allocate resources; profit motive; inequality but efficiency\nCommand: government owns means of production; equality goal; inefficiency, shortages\nMixed economy (UK): mostly market with government intervention in healthcare, education, utilities\nProfit motive: firms produce what consumers want (price signal)',
  'Government Objectives & Policy': 'Phillips curve: inverse relationship between inflation and unemployment (short run)\nAt 2% inflation: unemployment ~4-5%; At 0% inflation: unemployment ~6-7%\nStagflation (1970s): both high inflation AND high unemployment — broke the simple Phillips curve\nLong run: vertical LRAS at natural rate of unemployment; monetary policy only causes inflation',
  'Exchange Rates': 'If £1=$1.30 and price is £500:\nUS dollar price = 500×1.30=$650\nIf pound depreciates to £1=$1.10:\nUS price = 500×1.10=$550 (exports CHEAPER → more competitive)\nImports more expensive → imported inflation\nJ-curve effect: initially trade balance worsens after depreciation, then improves',
  'International Trade & Exchange Rates': 'Comparative advantage: Country A makes 10 cars OR 20 tonnes wheat per worker.\nCountry B makes 6 cars OR 15 tonnes wheat per worker.\nOC of car for A=2 wheat; for B=2.5 wheat → A has CA in cars\nOC of wheat for A=0.5 car; for B=0.4 car → B has CA in wheat\nBoth gain from specialisation and trade',
  'Macroeconomic Aims & Indicators': 'UK macroeconomic objectives:\n- Economic growth: real GDP growth 2-3% per year target\n- Low inflation: Bank of England 2% CPI target\n- Low unemployment: natural rate ~4-5%; cyclical unemployment tackled by demand stimulus\n- Balance of payments: sustainable current account deficit\nConflict: reducing inflation (raise rates) may increase unemployment',
  'Government Intervention': 'Minimum wage set above equilibrium (£10.42/hr, above market rate £8):\nLabour supply > demand → unemployment = QS-QD\nBenefit: workers earn more; higher spending; reduces poverty\nCost: employers cut jobs; especially affects small firms and youth employment',
  'Market Failure & Government Intervention': 'Carbon tax of £40/tonne CO₂:\nRaises cost of production for polluters → supply shifts left → price rises → consumption falls\nTax = marginal external cost → internalises the externality\nAlternative: cap-and-trade → set total emissions cap, firms trade permits\nEvaluate: tax certain about price not quantity; permits certain about quantity not price',
  'Market Failure': 'Public goods: non-excludable (cannot stop free riders) + non-rival (one person\'s use doesn\'t reduce availability)\nExamples: national defence, lighthouses, flood defences\nFree rider problem → market provides zero → government must provide\nQuasi-public: roads (excludable but rival at congestion); parks (non-excludable, non-rival until crowded)',
  'Demand and Supply': 'Equilibrium: P=£20, Q=500 units\nNew tax of £5/unit: supply shifts left (higher cost per unit)\nNew equilibrium: P=£23 (consumer pays £3 more), Q=450\nIncidence: consumer bears £3 (60%), producer bears £2 (40%)\nDistribution depends on PED/PES ratio',
  'Costs, Revenue & Profit': 'Fixed costs: £50,000 (rent, insurance)\nVariable: £8/unit. Total cost at 3,000 units: 50,000+24,000=£74,000\nAverage cost=£74,000/3,000=£24.67\nRevenue at price £30: 3,000×30=£90,000\nProfit=£90,000-£74,000=£16,000\nBreak-even: 50,000/(30-8)=2,273 units',
  'Finance': 'Investment appraisal — payback period:\nInitial investment: £100,000\nYear 1: £30,000; Year 2: £40,000; Year 3: £35,000\nPayback: after 2 years = £70,000; remaining £30,000 in Year 3\nPayback period = 2 + 30/35 = 2.86 years ≈ 2 years 10 months',
  'Cash Flow & Finance Sources': 'Net present value (NPV):\nDiscount rate 10%. Year 1 cash flow £50,000: PV=50,000/1.1=£45,455\nYear 2: £60,000 PV=60,000/1.21=£49,587\nYear 3: £40,000 PV=40,000/1.331=£30,052\nTotal PV=£125,094. Initial cost £100,000. NPV=+£25,094 → accept project',
  'Break-Even Analysis': 'Contribution = selling price − variable cost = £25−£10 = £15\nBreak-even = fixed costs ÷ contribution = £45,000÷£15 = 3,000 units\nMargin of safety: if sales=4,200: MoS=1,200 units or (1,200×£25)=£30,000\nProfit at 4,200 units: (4,200−3,000)×£15 = £18,000',
  'Human Resources': 'Calculate labour turnover rate:\nStaff left=12; average workforce=80\nRate=12/80×100=15%\nHigh rate costs: recruitment (£3,000/hire×12=£36,000) + training + lost productivity\nMotivation strategies: Herzberg — hygiene factors (salary, conditions) prevent dissatisfaction; motivators (achievement, recognition) increase motivation',
  'Motivation & Leadership': 'Taylor (Scientific Management): time and motion study → optimal method → piece-rate pay\nMaslow hierarchy: physiological→safety→social→esteem→self-actualisation\nApplication: new employees need physiological (salary) and safety (job security) satisfied first\nMcGregor Theory X: workers are lazy, need control. Theory Y: workers motivated, seek responsibility\nLeadership styles: autocratic (fast decisions, crisis) vs democratic (better buy-in, creative tasks)',
  'Digital Marketing & Brand': 'PPC (pay-per-click): pay £0.50/click; 1000 clicks=£500 spend\nIf 50 conversions at £20 profit each: £1,000 revenue − £500 ad spend = £500 profit\nROI=(500/500)×100=100%\nSEO: keyword optimisation, backlinks, page speed improve organic ranking\nConversion rate optimisation: A/B test headlines, CTA buttons',
  'Market Research & Segmentation': 'Sampling methods:\nRandom: each person equal chance — most unbiased but expensive\nStratified: proportional representation of groups (e.g. 60% female if 60% of population)\nQuota: fill preset numbers per group — quick but non-random\nCluster: sample from selected geographic areas — cheaper but may not represent all\nSample of 200 from population 10,000: margin of error ~±7% at 95% confidence',
  'Income Statement (Trading Account)': 'Opening inventory £4,000 + Purchases £22,000 − Closing inventory £3,500 = Cost of Sales £22,500\nSales £35,000 − COS £22,500 = Gross Profit £12,500\nLess: wages £4,000, rent £2,000, electricity £500 = total expenses £6,500\nNet Profit = £12,500−£6,500 = £6,000\nGross profit margin = 12,500/35,000×100 = 35.7%',
  'Balance Sheet (Statement of Financial Position)': 'Non-current assets: equipment £15,000; premises £40,000 = £55,000\nCurrent assets: inventory £3,500; debtors £4,200; cash £1,300 = £9,000\nCurrent liabilities: creditors £2,800; overdraft £500 = £3,300\nNet current assets (working capital) = £9,000−£3,300 = £5,700\nNet assets = 55,000+5,700 = £60,700 = Capital employed',
  'Books of Prime Entry': 'Sales day book:\nDate | Customer | Invoice No. | Amount\n01/05 | Ahmed Ltd | 101 | £2,400\n03/05 | Baker Co | 102 | £1,800\nTotal £4,200 → posted to Sales account (credit) and individual debtor accounts (debit)\nPurpose: records all credit sales before posting to ledger; provides audit trail',
  'Accruals & Prepayments': 'Annual insurance £2,400 paid 1 Oct. Year ends 31 Dec.\nExpense for 3 months = 2,400×3/12 = £600\nPrepayment (asset) = £1,800 (paid for future period)\nAccrued wages: staff worked last 3 days of month, £450 unpaid:\nDR wages £450 / CR accruals £450',
  'Adjustments to Accounts': 'Depreciation adjustment:\nMachine cost £8,000; 20% reducing balance\nYear 1: 8,000×20%=£1,600 → NBV=£6,400\nDR depreciation £1,600 / CR accumulated depreciation £1,600\nBad debt: debtor £300 irrecoverable:\nDR bad debts £300 / CR debtors control £300',
  'Enzymes': 'Enzyme kinetics:\nAt low substrate: rate ∝ substrate concentration (enzyme not saturated)\nAt high substrate: rate plateaus at Vmax (all active sites occupied — rate-limiting step is enzyme-substrate complex breakdown)\nKm (Michaelis constant): substrate concentration at ½Vmax\nLow Km = high affinity for substrate\nTemperature coefficient Q₁₀: for every 10°C rise, rate approximately doubles (until denaturation)',
  'Movement In & Out of Cells': 'Osmosis experiment: potato chip in 1 mol/dm³ sucrose\nWater potential of potato > water potential of solution\n→ water moves OUT by osmosis → chip loses mass, becomes flaccid\nActive transport: Na⁺/K⁺ pump moves 3Na⁺ out, 2K⁺ in, using ATP\nRequired: carrier protein + ATP (contrasts with diffusion: no energy needed)',
  'Digestion & Enzymes': 'Protein digestion:\nMouth: none (no protease)\nStomach: pepsin (pH 2, optimum ~2) → polypeptides\nSmall intestine: trypsin (from pancreas, pH 7-8) → dipeptides\nDipeptidase (brush border): dipeptides → amino acids\nAbsorption: amino acids by active transport into villi; lipids as micelles\nBile: emulsifies fat (increases surface area for lipase)',
  'Circulation': 'Blood pressure through circulatory system:\nAorta: 120 mmHg (systolic); arteries: ~100mmHg; arterioles: ~40mmHg\nCapillaries: ~15-25mmHg; veins: ~5-10mmHg; vena cava: ~2mmHg\nFiltration at capillary: hydrostatic pressure (pushes fluid out) > osmotic pressure (pulls in)\nat venous end: osmotic > hydrostatic → fluid reabsorbed\nExcess fluid returned by lymphatic system',
  'Disease & Immunity': 'Active immunity: body produces own antibodies (natural=infection; artificial=vaccine)\nPassive immunity: antibodies received from another source (natural=breast milk; artificial=injection)\nActive: slow to develop, long-lasting (memory cells)\nPassive: immediate protection, short-lived (no memory cells)\nHerd immunity threshold: depends on R₀. For measles R₀≈15, need ~93% immune',
  'Human Biology': 'BMI = weight(kg) / height²(m²)\nBMI 18kg, height 1.80m: BMI=18×18/1.80²... wait\nPerson 75kg, 1.75m: BMI=75/3.0625=24.5 (healthy range 18.5-25)\nCaloric requirement: BMR 1800 kcal/day; active person ×1.5=2700 kcal\nExcess: 3500 kcal excess ≈ 1 pound (0.45kg) fat gain',
  'Body Systems': 'Homeostasis example — body temperature:\nNormal: 37°C. Too hot: vasodilation (blood to skin), sweating (evaporative cooling)\nToo cold: vasoconstriction, shivering (muscle contractions generate heat), piloerection\nNegative feedback: response opposes the change\nSetpoint maintained by hypothalamus (thermoregulation centre)',
  'Coordination & Homeostasis': 'Negative feedback: blood glucose\n8.0 mmol/L (above normal 4-6):\n→ pancreas β-cells release insulin\n→ liver converts glucose to glycogen (glycogenesis)\n→ cells increase glucose uptake\n→ blood glucose returns to 5 mmol/L\nIf 3.0 mmol/L (below normal):\n→ glucagon from α-cells → glycogenolysis → glucose released',
  'Cell Biology': 'Mitosis produces 2 genetically identical diploid cells (for growth/repair)\nMeiosis produces 4 genetically different haploid cells (for reproduction)\nPhases of mitosis: PMAT — Prophase (chromosomes condense), Metaphase (align at equator), Anaphase (chromatids separate), Telophase (new nuclei form)\nCell cycle: G1 (growth) → S (DNA replication) → G2 (preparation) → M (mitosis)',
  'Biological Molecules': 'Test for protein: Biuret reagent. Positive: blue→purple\nTest for glucose: Benedict\'s. Positive: blue→brick-red (heat needed)\nTest for starch: iodine solution. Positive: orange→blue-black\nTest for lipids: ethanol emulsion test. Positive: milky white precipitate\nAmino acids joined by peptide bonds (condensation reaction); broken by hydrolysis',
  'Genetic Engineering & Biotechnology': 'Insulin production by GM bacteria:\n1. Human insulin gene cut from DNA using restriction enzymes (EcoRI)\n2. Plasmid cut with same restriction enzyme → sticky ends\n3. Insulin gene inserted into plasmid (ligase seals)\n4. Recombinant plasmid introduced into E.coli\n5. Bacteria express human insulin → purified for diabetics\nEthical concerns: playing God, unintended consequences, patent issues',
  'Human Impact & Conservation': 'Trophic cascade: removing wolves from Yellowstone\nWolves removed → deer population exploded → overgrazing of vegetation → river banks eroded\nWolves reintroduced 1995: deer numbers down, grazing reduced, vegetation recovered, rivers more stable\nBiodiversity metrics: species richness (number of species) + evenness (relative abundance)\nConservation: in-situ (national parks, corridors) vs ex-situ (zoos, seed banks)',
  'Evolution & Natural Selection': 'Calculating allele frequencies (Hardy-Weinberg):\np²+2pq+q²=1 and p+q=1\nIf 16% homozygous recessive (q²=0.16): q=0.4, p=0.6\nHeterozygote frequency: 2pq=2×0.6×0.4=0.48=48%\nH-W equilibrium assumes: large population, random mating, no selection/mutation/migration',
  'Evolution & Biodiversity': 'Speciation by geographic isolation:\n1. Population divided by barrier (mountain range, river)\n2. Each population undergoes different mutations, natural selection\n3. Allele frequencies diverge\n4. Eventually populations are reproductively isolated\n5. Allopatric speciation complete\nSympatric: in same location, different niches or polyploidy (in plants)',
  'Atmosphere & Climate': 'Enhanced greenhouse effect:\nCO₂ from burning fossil fuels absorbs outgoing infrared radiation → more re-radiated back to Earth\nCurrent CO₂: ~420 ppm (pre-industrial: 280 ppm)\nFeedback: ice melts → less albedo → more absorption → more warming (positive feedback)\nOzone depletion: CFCs catalytically destroy O₃ → more UV-B → skin cancer, ecosystem damage',
  'Causes & Evidence of Climate Change': 'Evidence for climate change:\nInstrumental records: global average temperature +1.1°C since 1850\nIce cores: CO₂ and temperature correlated over 800,000 years\nSea level rise: 20cm rise since 1900 (thermal expansion + ice melt)\nPhenological changes: earlier spring flowering (3-4 weeks earlier)\nAttribution: IPCC "unequivocal" that human influence is main cause',
  'Renewable Energy': 'Compare electricity generation:\nSolar PV: UK capacity factor ~10% → 1MW panel generates 876 MWh/year\nWind (onshore): capacity factor ~25% → 1MW turbine generates 2,190 MWh/year\nNuclear: capacity factor ~85% → 1MW generates 7,446 MWh/year\nLevelised cost: solar and wind now cheapest new electricity globally (< £50/MWh)',
  'Ecosystems & Food Webs': 'Food web energy flow:\nGrass→rabbit→fox→eagle\nGrass: 100,000 kJ/m²/year → 10% efficiency at each level\nRabbit: 10,000 kJ; Fox: 1,000 kJ; Eagle: 100 kJ\nOnly 0.1% of energy in grass reaches eagle\nCarbon cycle: photosynthesis (CO₂ fixed), respiration (CO₂ released), decomposition, combustion',
  'Managing Human Impact': 'Eutrophication process:\n1. Fertiliser runoff → nitrates/phosphates in river\n2. Algal bloom (algae grow rapidly)\n3. Algae block sunlight → aquatic plants die\n4. Bacteria decompose dead plants → use up dissolved oxygen\n5. Fish and invertebrates die (hypoxic zone)\nSolutions: reduce fertiliser use, buffer strips, wetland filtration',
  'Immunity & Defence': 'Specific immune response:\n1. Pathogen enters body; antigens on surface identified as foreign\n2. Phagocyte engulfs and presents antigen (APC)\n3. T-helper cells activated → stimulate B cells\n4. B cells differentiate → plasma cells (produce antibodies) + memory B cells\n5. Antibodies: neutralise toxins, agglutinate bacteria (clump), opsonise (mark for phagocytosis)\nVaccination prevents step 1 becoming serious; memory cells give rapid secondary response',
  'Memory': 'Baddeley & Hitch working memory model:\nPhonological loop: stores verbal/acoustic information (inner ear + inner voice)\nVisuospatial sketchpad: processes visual and spatial information\nCentral executive: allocates attention, controls other systems\nEpisodic buffer: integrates info from multiple sources + long-term memory\nEvaluation: supported by dual-task studies; explains individual differences in STM capacity',
  'Forgetting': 'Interference theory:\nProactive interference: OLD learning interferes with NEW (e.g. old phone number blocks new)\nRetroactive interference: NEW learning disrupts OLD memories\nTricer & Bahrick: found high proactive interference in learning foreign language vocabulary\nDecay theory: trace fades through disuse (little supporting evidence — Bahrick 1975 showed 50yr memory retention)\nRetrieval failure: context-dependent memory (Godden & Baddeley: divers recalled underwater words better underwater)',
  'Learning': 'Bandura Social Learning Theory (Bobo Doll 1961):\n66 children watched adult model beat inflatable doll\nAggressive model group: children reproduced 88% of aggressive acts\nControl: far fewer aggressive acts\nMediating processes: Attention → Retention → Reproduction → Motivation (ARRM)\nCritique: demand characteristics; children may have thought it acceptable to hit toy specifically',
  'Attachment (Bowlby)': 'Bowlby\'s Monotropy theory:\nInfants have innate drive to form attachment with ONE primary caregiver (usually mother)\nCritical period: 0-2.5 years for forming attachment\nInternal working model: template for future relationships\nMaternalDeprivation hypothesis: separation from mother → permanent emotional damage\nCounter: Rutter (1981) — multiple attachments possible; privation (never formed) more harmful than deprivation',
  'Cognitive Development (Piaget)': 'Conservation of liquid task:\nPre-operational child (age 5): pours water into taller, narrower container\n"Which has more?" → Child: "The tall one" (centration on height only)\nConcrete operational (age 7+): understands volume unchanged → conservation achieved\nMcGarrigle & Donaldson (Naughty Teddy): children showed conservation earlier when task seemed accidental → Piaget underestimated children',
  'Conformity & Social Influence': 'Asch (1951): line length judgment task\n6 confederates gave wrong answer; 1 real participant\n75% of real participants conformed at least once; 37% of all answers wrong\nVariables increasing conformity: group size (up to 3), task difficulty, face-to-face\nVariables decreasing: presence of ally, non-unanimous majority, answer written privately\nTypes: compliance (public agreement only), identification, internalisation (genuine belief change)',
  'Obedience': 'Milgram (1963) baseline: 65% delivered 450V\nSituational factors increasing obedience:\nAuthority figure present (14% if absent), prestigious location (Yale → less obedience in run-down building), uniform (lab coat), gradual escalation, buffers\nDestructive obedience: agentic state — individual becomes instrument of authority; loses moral responsibility\nKilham & Mann replication in Australia: 40% obedient; cross-cultural variation',
  'Biological Psychology': 'Twin studies: MZ (identical, 100% genes shared) vs DZ (50%)\nIf MZ concordance > DZ concordance: genetic influence on trait\nSchizophrenia: MZ concordance ~48%; DZ ~17% → strong but not 100% genetic (environment also matters)\nNeurotransmitters: dopamine hypothesis of schizophrenia (excess dopamine)\nAntipsychotics (chlorpromazine) block D2 receptors → reduce positive symptoms',
  'Individual Differences': 'Case study method:\nAdvantage: rich, detailed data; studies rare conditions (HM, Phineas Gage)\nDisadvantage: cannot generalise; unique individual; retrospective data unreliable\nIdiographic approach: study unique individual (case study, personal construct)\nNomothetic: seek universal laws (experiments, surveys, standardised tests)\nFreud used idiographic; Watson used nomothetic (behaviourism)',
  'Methods & Design': 'Experimental design comparison:\nIndependent groups: different participants in each condition\n+ no order effects; - participant variables (individual differences)\nRepeated measures: same participants in all conditions\n+ controls individual differences; - order effects, demand characteristics\nMatched pairs: matched on key variable; middle ground\nCounterbalancing (ABBA): controls order effects in repeated measures',
  'Key Research Concepts': 'Reliability vs Validity:\nReliability: consistency — test-retest (same result over time), inter-rater (observers agree)\nValidity: measures what it claims to — internal (controls confounding variables), external (generalises to real world)\nStandardisation: same procedure every time → increases reliability\nOperationalisation: define variables precisely (e.g. "stress" = cortisol level in saliva)\nEthics: informed consent, right to withdraw, debriefing, confidentiality, protection from harm',
  'Evaluating Research': 'Critiquing a study:\nSample: size (n=20 limited), representativeness (all male → cannot generalise to females), self-selected (volunteer bias — often more motivated/cooperative)\nMeasurement: self-report questionnaire — social desirability bias; leading questions\nControl: extraneous variables; demand characteristics (guessing aim and conforming)\nStrength of conclusion: correlation ≠ causation; confounding variables\nEcological validity: lab experiment → artificial behaviour; field experiment → more natural but less control',
  'Approaches in Psychology': 'Psychodynamic approach (Freud):\nConscious (tip of iceberg) → small; Preconscious → larger; Unconscious (bulk) → drives, repressed memories\nStructure of personality: Id (pleasure principle, innate), Ego (reality principle, mediates), Superego (morality principle, socialised)\nDefence mechanisms: repression (pushing unconscious), projection (attributing own feelings to others), displacement, rationalisation\nCritique: unfalsifiable; overdetermines importance of sex; based on case studies of neurotic patients',
  'Hormones & Behaviour': 'Stress response — HPA axis:\n1. Stressor perceived by amygdala → signals hypothalamus\n2. CRH released → anterior pituitary releases ACTH\n3. ACTH → adrenal cortex releases cortisol\n4. Cortisol: raises blood sugar, suppresses immune system (long-term)\nSAM axis (fight or flight): adrenaline released within seconds\nChronic stress effects: hypertension, immunosuppression, hippocampal damage (memory problems)',
  'Abnormality & Mental Health': 'Definitions of abnormality:\nStatistical infrequency: below IQ 70 = abnormal; problem — high IQ also "abnormal"\nDeviation from social norms: context-dependent; cultural relativism problem\nFailure to function adequately: cannot maintain daily life; personal distress indicator\nDeviation from ideal mental health (Jahoda): positive criteria include self-actualisation, autonomy, resistance to stress\nEvaluation: all definitions have cultural bias; none sufficient alone',
  'Comparing Perspectives': 'Evaluate biological vs behaviourist explanation of depression:\nBiological: serotonin deficiency; genetic predisposition (MZ concordance ~50%)\nTreatment: SSRIs (increase serotonin) effective for 50-70% of patients\nBehaviourist: learned helplessness (Seligman) — past experience of uncontrollable events\nTreatment: cognitive behavioural therapy (CBT) — identifies and challenges negative thought patterns\nConclusion: diathesis-stress model — biological vulnerability + environmental trigger',
  'Medieval Medicine (c1250–1500)': 'Four Humours theory (Galen, 2nd century AD, still dominant in medieval period):\nBlood (air), Phlegm (water), Yellow bile (fire), Black bile (earth)\nIllness: imbalance of humours\nTreatment: bloodletting (restore balance), purging, herbal remedies\nRole of Church: God caused disease as punishment; prayer and pilgrimage as cure\nWhy ideas persisted: Church controlled education and hospitals; Galen supported by Church; no scientific method',
  'Causes of World War II': 'Long-term: Treaty of Versailles humiliated Germany (reparations £6.6bn, war guilt, loss of territory, army limited to 100,000)\nRise of Hitler: exploited resentment; promised to reverse Versailles; 1933 Chancellor\nAppeasement: Munich Agreement 1938 — Chamberlain gave Hitler Sudetenland; hoped to avoid war\nHitler saw appeasement as weakness; invaded Poland September 1939\nSoviet-Nazi Pact: Hitler secured eastern border before attacking west',
  'Cold War 1945–1991': 'Truman Doctrine 1947: USA would support free nations against communist takeover (Greece, Turkey)\nMarshall Plan 1947: $13bn to rebuild Western Europe; strategic — prosperous democracies less likely to turn communist\nBerlin Blockade 1948-49: USSR blocked road/rail access to West Berlin; USA/UK Berlin Airlift 322,000 flights\nCuban Missile Crisis 1962: closest to nuclear war; resolved by USA removing missiles from Turkey + USSR from Cuba\nDetente 1970s: SALT treaties limited nuclear weapons',
  'Manifest Destiny & Migration': 'Manifest Destiny: belief that USA had God-given right to expand from Atlantic to Pacific coast\n"Go West, Young Man" (1865): homestead act gave 160 acres free to settlers\nImpact on Plains Indians: forced onto reservations; buffalo herds destroyed (200m → near-extinct by 1890)\nGold Rush 1848: 300,000 migrants to California; statehood 1850\nTranscontinental Railroad 1869: connected East to West; enabled mass migration; displaced Native Americans',
  'Cold War Crises & Détente': 'Bay of Pigs 1961: CIA-trained Cuban exiles invaded Cuba; failed embarrassingly; strengthened Castro and Soviet ties\nCuban Missile Crisis 1962 resolution:\n- JFK: naval blockade ("quarantine"); ultimatum to Khrushchev\n- Khrushchev: agreed to remove missiles IF USA pledged not to invade Cuba\n- Secret deal: USA also removed Jupiter missiles from Turkey\nDetente: SALT I (1972) — cap on ICBMs and SLBMs; Helsinki Accords (1975) recognised European borders',
  'Key Events of WWII': 'Operation Barbarossa June 1941: Germany invaded USSR with 3 million troops (largest invasion in history)\nBattle of Stalingrad 1942-43: turning point — German 6th Army encircled; 330,000 Germans surrendered\nD-Day June 6 1944: Allied landings in Normandy; 156,000 troops; largest seaborne invasion ever\nAtom bombs: Hiroshima (6 Aug) and Nagasaki (9 Aug) 1945; Japan surrendered 15 Aug 1945\nHolocaust: 6 million Jews and 5-6 million others systematically murdered',
  'Development & Sustainability': 'Brundtland definition: "development that meets the needs of the present without compromising the ability of future generations to meet their own needs"\nSustainable Development Goals (SDGs): 17 goals by 2030; e.g. SDG 7 (clean energy), SDG 13 (climate action)\nNiger case study: HDI=0.394 (177/191); GDP per capita $600; life expectancy 62; high birth rate\nIntervention: Oxfam water projects → reduced disease burden → children attend school more → education improves',
  'Map Skills & Data Interpretation': 'OS map: 1:50,000 scale. 2cm on map = 1km on ground.\nGrid reference: 6-figure. Easting first, then northing (always "along the corridor then up the stairs")\nContour lines: closer together = steeper slope; concentric circles = hill; V-shape pointing upstream = valley\nChloropleth map: darker shade = higher value; shows spatial distribution\nDot distribution map: each dot = fixed number of items; shows clustering',
  'Fieldwork & Investigation': 'River fieldwork: measure discharge = width × depth × velocity\nWidth: tape measure across channel\nDepth: depth gauge at regular intervals; average of readings\nVelocity: float method (time for float over 10m) or flow meter\nHypothesis: "velocity increases downstream" — test at 3 sites\nProcessing data: Spearman\'s rank correlation coefficient; r=+0.86 suggests strong positive correlation',
  'Natural Environment': 'Tectonic plates:\nConvergent (collision): oceanic + continental → subduction → volcanoes and fold mountains (Andes)\nDivergent: plates move apart → new ocean floor formed (Mid-Atlantic Ridge)\nTransform: plates slide past → earthquakes, no volcanoes (San Andreas Fault)\nMeasuring earthquakes: Richter scale (logarithmic — magnitude 7 is 10× stronger than 6)',
  'Urban Issues': 'Urban heat island:\nCity centre 3-5°C warmer than surrounding countryside\nCauses: dark surfaces absorb heat, reduced vegetation, waste heat from buildings/vehicles, reduced wind speed\nSolutions: green roofs, urban parks, cool pavements (high albedo)\nLondon case study: Thames Barrier protects against flooding; congestion charge reduced traffic 15%',
  'Industry & Globalisation': 'Deindustrialisation in UK:\n1960s: steel, coal, shipbuilding dominant; 1980s: declined due to cheaper overseas competition\nService sector grew: financial services (London), healthcare, education\nMNC location decisions: labour costs, skills, infrastructure, market access, tax incentives\nTNCs (transnational corporations): production in multiple countries; e.g. Apple designs in USA, manufactures in China, sells globally',
  'Migration': 'Economic migration: Polish workers to UK after EU expansion 2004\nEstimated 600,000 Poles migrated to UK 2004-2008\nBenefits (host): fills labour gaps, skills, tax revenue, cultural diversity\nCosts (host): pressure on housing, schools, NHS; social tensions\nBenefits (source): remittances sent home (global remittances $700bn/year), reduces unemployment\nCosts (source): brain drain; loss of young working population; dependency on remittances',
  'Air Pollution': 'Photochemical smog formation:\n1. Sunlight + NO₂ → NO + O (atomic oxygen)\n2. O + O₂ → O₃ (ground-level ozone)\n3. O₃ + unburned hydrocarbons → peroxyacetyl nitrates (PANs) and aldehydes\nHealth effects: respiratory disease, eye irritation, reduced lung function\nSolutions: catalytic converters (convert NOₓ, CO, HC to N₂, CO₂, H₂O), low emission zones, electric vehicles',
  'Water & Sanitation': 'Water cycle quantification:\nGlobal water: 97.5% saltwater; 2.5% freshwater; 70% of freshwater frozen\nWater stress: < 1,700m³/person/year (Egypt: 570m³ — severe stress)\nSanitisation coverage: 2.3 billion people lack basic sanitation\nWater treatment: coagulation (alum) → flocculation → sedimentation → filtration → disinfection (chlorine)\nCholera: spread by faecal contamination of water; killed 40,000 in Yemen 2017',
  'Religion & Ethics': 'Situation Ethics (Joseph Fletcher, 1966):\nOnly absolute rule: act with agape (unconditional love)\nPrinciples: pragmatic, relativistic, positivistic, personalistic\nExample: lying to save a life is morally right if it is the most loving act\nStrength: flexible, person-centred\nWeakness: subjective; could justify any act claiming it is "loving"; ignores social consequences',
  'Christian Ethics': 'Natural Law (Aquinas): God-given purpose for human actions; moral = fulfils natural purpose\nAbsolute: always apply regardless of consequences\nPrimary precepts: preserve life, reproduce, educate, worship God, live in society\nApplication: contraception wrong (blocks reproduction); euthanasia wrong (against preserving life)\nContrast with Utilitarian: Natural Law → absolute rules; Utilitarianism → best consequences determine rightness',
  'Islamic Practices': 'Five Pillars application:\nSalah: 5 prayers at fixed times (Fajr, Dhuhr, Asr, Maghrib, Isha); face Mecca; spiritual discipline\nZakat: 2.5% of savings held for one year above nisab threshold (≈85g gold equivalent)\nSawm: Ramadan fasting sunrise to sunset; promotes self-discipline and empathy for the poor\nHajj: required once if physically/financially able; Tawaf (7 circles of Kaaba); Sa\'i (walking between Safa and Marwa)',
  'Buddhist Ethics': 'Five Precepts: no killing, no stealing, no sexual misconduct, no lying, no intoxicants\nApplied to environment: First Precept → protect all sentient beings → environmental responsibility\nMiddle Way: avoid extremes of indulgence and asceticism\nKarma: intention behind action determines karmic consequence\nEngaged Buddhism (Thich Nhat Hanh): apply Buddhist ethics to social/political issues (peace activism)',
  'Jewish Beliefs & Practices': 'Covenant with Abraham: circumcision as sign; God\'s promise of land and descendants\nTorah (613 mitzvot): 248 positive, 365 negative commandments\nShabbat: sunset Friday to Saturday night; no work; candles lit, kiddush wine, synagogue attendance\nKosher laws: no pork or shellfish; meat and dairy not mixed; animals must be humanely slaughtered\nYom Kippur (Day of Atonement): 25-hour fast; seek forgiveness from God and from those wronged',
  'Edexcel Theme 1: Identity & Culture': 'Me, my family and friends (key vocabulary):\nJe m\'entends bien avec ma famille. (I get on well with my family.)\nNous nous disputons parfois. (We argue sometimes.)\nMon meilleur ami est généreux et compréhensif. (My best friend is generous and understanding.)\nValeurs familiales: important de se respecter et de se soutenir mutuellement.',
  'Edexcel Theme 2: Local & Global': 'Technology and social media:\nLes réseaux sociaux ont un impact positif et négatif sur notre vie.\nD\'un côté, ils nous permettent de rester en contact... D\'un autre côté, ils peuvent être dangereux.\nEnvironment: Le réchauffement climatique est un problème mondial grave.\nIl faut réduire les émissions de CO₂ en utilisant les énergies renouvelables.',
  'Edexcel Theme 3: Study & Employment': 'Future jobs (French):\nJe voudrais devenir médecin parce que je veux aider les autres.\nAprès mes études, j\'espère travailler dans un domaine créatif.\nIl est important de continuer ses études pour avoir de meilleures perspectives.\nMon stage en entreprise m\'a aidé à découvrir le monde du travail.',
  'Nouns, Articles & Adjectives': 'Spanish gender rules:\nMost -o words → masculine (el libro), most -a words → feminine (la casa)\nExceptions: el día, el mapa, el problema (masculine despite -a)\nDefinite article: el/la/los/las\nIndefinite: un/una/unos/unas\nAgreement: el libro rojo / la casa roja / los libros rojos / las casas rojas',
  'Adjectives & Agreement': 'French adjective agreement with être:\nIl est grand → Elle est grande → Ils sont grands → Elles sont grandes\nBEAPS adjectives before noun:\nun beau garçon → une belle fille → de beaux enfants\nComparative: plus grand(e) que (taller than)\nSuperlative: le/la/les plus grand(e)(s) (the tallest)',
  'Common Irregular Past Participles': 'Key irregular past participles:\nfaire → fait, être → été, avoir → eu, aller → allé, prendre → pris\nvenir → venu, voir → vu, savoir → su, pouvoir → pu, vouloir → voulu\nWith avoir: J\'ai fait / il a pris\nWith être (MRS VANDERTRAMPP): Elle est venue / ils sont allés\nAgreement with avoir + preceding direct object: Les lettres qu\'il a écrites (f.pl. → écrites)',
  'Listening & Reading Skills': 'Listening strategies for Spanish/French:\n1. Read questions BEFORE listening to know what to focus on\n2. Note key words: numbers, times, names, opinions\n3. Distinguish similar sounds: pero/perro in Spanish; son/sont in French\n4. Negative expressions: ne...pas, no, jamais, nunca — change meaning completely\n5. Cognates help but beware false friends: "sensible" in French means "sensitive" not "sensible"',
  'Grammar Essentials': 'Ser vs Estar (Spanish) — key rule:\nSer: permanent identity (origin, profession, appearance, material, time)\nEstar: temporary state, location, ongoing action\nExamples:\nSoy médico. (I am a doctor — profession, ser)\nEstoy cansado. (I am tired — temporary state, estar)\nLa mesa es de madera. (The table is made of wood — material, ser)\nEl libro está en la mesa. (The book is on the table — location, estar)',
};

// Fix injection: handle ALL occurrences of same title
let added = 0;
let searchFrom = 0;

while (true) {
  // Find next topic title with points array
  const re = /title:'([^']+)',\s*points:\[/g;
  re.lastIndex = searchFrom;
  const m = re.exec(src);
  if (!m) break;

  const title = m[1];
  const titleIdx = m.index;

  // Move searchFrom forward so next iteration finds the next one
  searchFrom = titleIdx + 1;

  const we = WORKED[title];
  if (!we) continue;

  // Check if this specific topic object already has workedExample
  // Scan forward from this titleIdx to find the closing of the topic
  const pointsStart = src.indexOf('points:[', titleIdx);
  if (pointsStart === -1 || pointsStart - titleIdx > 200) continue;

  let depth = 0, i = pointsStart + 7, pointsEnd = -1;
  while (i < src.length) {
    if (src[i] === '[') depth++;
    else if (src[i] === ']') { if (depth === 0) { pointsEnd = i; break; } depth--; }
    i++;
  }
  if (pointsEnd === -1) continue;

  // Find the topic closing },  — scan forward from pointsEnd
  // Find closing brace of topic object
  let braceDepth = 0, j = titleIdx;
  while (j < src.length) {
    if (src[j] === '{') braceDepth++;
    else if (src[j] === '}') { braceDepth--; if (braceDepth === 0) break; }
    j++;
  }
  const topicEnd = j;
  const topicSrc = src.slice(titleIdx, topicEnd);

  if (topicSrc.includes('workedExample')) continue;

  // Find last field end
  let lastFieldEnd = pointsEnd;
  const checkArr = (kw) => {
    const s2 = src.indexOf(kw, lastFieldEnd);
    if (s2 === -1 || s2 - lastFieldEnd > 600) return;
    let d = 0, jj = s2 + kw.length - 1;
    while (jj < src.length) { if(src[jj]==='[') d++; else if(src[jj]===']'){if(d===0){lastFieldEnd=jj;return;}d--;} jj++; }
  };
  checkArr('examTips:['); checkArr('commonMistakes:[');

  const wep = src.indexOf('workedExample:`', lastFieldEnd);
  if (wep !== -1 && wep - lastFieldEnd < 600) { let jj=wep+15; while(jj<src.length&&src[jj]!=='`')jj++; lastFieldEnd=jj; }

  const safeWe = we.replace(/\\/g,'\\\\').replace(/`/g,'\\`').replace(/\$/g,'\\$');
  const injection = ', workedExample:`' + safeWe + '`';
  src = src.slice(0, lastFieldEnd+1) + injection + src.slice(lastFieldEnd+1);
  added++;

  // Adjust searchFrom for the inserted text
  searchFrom = lastFieldEnd + 1 + injection.length;
}

console.log('workedExample added:', added);

try {
  new Function(src);
  console.log('SYNTAX OK');
  writeFileSync('app.js', src);
  console.log('Written');
} catch(e) {
  console.log('SYNTAX ERROR:', e.message);
  const lines = src.split('\n');
  for (let i=0; i<lines.length; i++) {
    try { new Function(lines.slice(0,i+1).join('\n')); } catch(e2) {
      if (e2.message===e.message){console.log('Line',i+1,':',lines[i].slice(0,120));break;}
    }
  }
}
